#!/usr/bin/env bash
# Generate a privacy-clean markdown report from hooks-compact telemetry.
#
# Usage:
#   ./scripts/team-report.sh              # last 7 days
#   ./scripts/team-report.sh --days=30    # last 30 days
#   ./scripts/team-report.sh --db=path    # custom DB path
#
# Output: pastable markdown for Slack/Teams.
#
# Privacy: only command first-tokens (already stored that way),
#          outcome, counts, and savings percentages.
#          NO paths, args, hostnames, session IDs, or user identifiers.

set -euo pipefail

# ── Defaults ──────────────────────────────────────────────────────────────
DAYS=7
DB_PATH="$HOME/.amplifier/hooks-compact/telemetry.db"

# ── Parse flags ───────────────────────────────────────────────────────────
for arg in "$@"; do
  case "$arg" in
    --days=*) DAYS="${arg#--days=}" ;;
    --db=*)   DB_PATH="${arg#--db=}" ;;
    --help|-h)
      echo "Usage: $0 [--days=N] [--db=PATH]"
      echo "  --days=N   Query window in days (default: 7)"
      echo "  --db=PATH  Path to telemetry.db (default: ~/.amplifier/hooks-compact/telemetry.db)"
      exit 0
      ;;
    *)
      echo "Unknown flag: $arg" >&2
      echo "Usage: $0 [--days=N] [--db=PATH]" >&2
      exit 1
      ;;
  esac
done

# ── Validate ──────────────────────────────────────────────────────────────
if [ ! -f "$DB_PATH" ]; then
  echo "No telemetry database found at: $DB_PATH"
  echo "The hook has not logged any events yet, or the DB path is wrong."
  echo "Use --db=PATH to specify a custom location."
  exit 0
fi

if ! command -v sqlite3 &>/dev/null; then
  echo "Error: sqlite3 is required but not found in PATH." >&2
  exit 1
fi

# ── Query ─────────────────────────────────────────────────────────────────
CUTOFF=$(date -u -v-${DAYS}d +"%Y-%m-%dT%H:%M:%S" 2>/dev/null \
      || date -u -d "${DAYS} days ago" +"%Y-%m-%dT%H:%M:%S" 2>/dev/null \
      || date -u +"%Y-%m-%dT%H:%M:%S")

TOTAL=$(sqlite3 "$DB_PATH" \
  "SELECT COUNT(*) FROM compression_log WHERE timestamp >= '$CUTOFF' AND outcome IS NOT NULL;")

if [ "$TOTAL" -eq 0 ] 2>/dev/null; then
  echo "## hooks-compact telemetry — last $DAYS days"
  echo ""
  echo "No data in the query window (since $CUTOFF)."
  echo ""
  echo "This is normal if the hook was just installed or no bash commands were run."
  exit 0
fi

DATE_RANGE=$(sqlite3 "$DB_PATH" \
  "SELECT MIN(date(timestamp)) || ' → ' || MAX(date(timestamp))
   FROM compression_log WHERE timestamp >= '$CUTOFF' AND outcome IS NOT NULL;")

# ── Generate report ───────────────────────────────────────────────────────
cat << EOF
## hooks-compact telemetry — last $DAYS days

**Period:** $DATE_RANGE
**Total bash events:** $TOTAL

| Command | Outcome | Count | % of Total | Avg Savings |
|---------|---------|------:|----------:|------------:|
EOF

sqlite3 -separator '|' "$DB_PATH" << EOSQL |
SELECT
    command,
    COALESCE(outcome, 'legacy'),
    COUNT(*),
    ROUND(100.0 * COUNT(*) / $TOTAL, 1),
    ROUND(AVG(savings_pct), 1)
FROM compression_log
WHERE timestamp >= '$CUTOFF'
  AND outcome IS NOT NULL
GROUP BY command, outcome
ORDER BY COUNT(*) DESC, command ASC;
EOSQL
while IFS='|' read -r cmd outcome count pct avg_savings; do
  printf "| %-7s | %-11s | %5s | %8s%% | %9s%% |\n" \
    "$cmd" "$outcome" "$count" "$pct" "$avg_savings"
done

echo ""
echo "_Generated by \`scripts/team-report.sh\` — command names only, no paths/args/hostnames._"
